### ISSUE TITLE
Ubuntu 18.04.2 LTS render error

### ISSUE THREAD

**Issue by icode** [gliheng/flutter-rs#11] opened 2019-02-19 03:15 UTC
```
$ ./scripts/run.py
>>> Building flutter bundle
>>> Building rust project
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `/home/icode/projects/flutter-rs/target/debug/flutter-app-demo`
flutter: Observatory listening on http://127.0.0.1:50300/
>>> Attaching dart debugger
```
![2019-02-19 11-12-28](https://user-images.githubusercontent.com/972959/52987745-61ca3c00-3437-11e9-876a-c923008d9756.png)

**Comment by gliheng** [comment] 2019-02-19 08:27
Hi, this issue is a duplicate of https://github.com/gliheng/flutter-rs/issues/4  Please follow that issue for progress.

**Closed by gliheng** 2019-02-19 08:27 UTC
